# Conceptual 

# BroadCasting in Numpy
""" 
Broadcasting simply measns that numpy automatically performs arithmetic operations on array of different shapes of arrays.
"""

# How do you select all rows where a column value > 10 in a 2D array?
"""

"""

# Difference between .reshape() and .flatten()?
""" 
.reshape() method is used to reshape any kind of array like 1d 2d 3d into another shape just like 1d array of 6 elements can be reshape into 2d array of 3 rows and 2 columns and for 2d arrays we pass 2 values for rows and columns and for 3d arrays we pass 3 values for blocks, rows, columns
.flatten() method is used to faltten any multi dimension array into 1d array
"""

# How do you generate a random array of shape (5,5)?
"""
Array of shape (5,5) can be generated by using random() function and we use rand(), randn(), ranf(), randint() to generate random numbers. 
np.random.rand(5,5)

and we also use reshape() in it to reshape array of our need.
"""

# What does axis=0 vs axis=1 mean in np.sum()?
"""
axis = 0 means along the rows or operations perform on columns and axis = 1 means along the columns or operations along the rows  and when we use it in np.sum() function it works according to it.
"""

# Implementation
import numpy as np 
sensor_data = np.random.randint(2, 30, size = 12).reshape(3,4)
print("The Values of sensor data is as follow:\n", sensor_data)

# Statistics
mean = np.mean(sensor_data)
print("The mean of sensor_data is:\n", mean)

std = np.std(sensor_data)
print("The std of sensor_data is:\n", std)

# Z-score
z_score = (sensor_data - mean) / std
print("Z-score:\n", z_score)
