# Conceptual Questions
# BroadCasting in Numpy
""" 
Broadcasting simply measns that numpy automatically performs arithmetic operations on array of different shapes. It is a simple method to perform operations on shapes of different sizes. 
"""
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10], [20]])
final_arr = arr1 + arr2
print("The final array after broadcasting is:\n", final_arr)
print("\n")

# How do you select all rows where a column value > 10 in a 2D array?
"""
We use boolean masking to select all rows in which a column value is greater than 10. FOr example: in 2d array we select all rows and first column then we use boolean condition >10 to get the rows where column value is greater than 10.
"""
arr = np.array([[1,2,3],
                [11,12,13],
                [21,22,23]])
result = arr[arr[:,0] > 10] # will give us the rows where column value is greater than 10.   
print("Result:\n", result)
print("\n")   

# Difference between .reshape() and .flatten()?
""" 
.reshape() method is used to reshape any kind of array like 1d 2d 3d into another shape just like 1d array of 6 elements can be reshape into 2d array of 3 rows and 2 columns and for 2d arrays we pass 2 values for rows and columns and for 3d arrays we pass 3 values for blocks, rows, columns. reshape always return a view of original array and it does not change the original array.

.flatten() method is used to faltten any multi dimension array into 1d array. faltten always return a copy of the original array and it doens't change the original array.
"""
arr = np.array([[1,2,3],
                [4,5,6]])
reshaped = arr.reshape(3,2)
print("Reshaped array:\n", reshaped)
print("\n")   
flattened = arr.flatten()
print("Flattened array:\n", flattened)
print("\n")

# How do you generate a random array of shape (5,5)?
"""
Array of shape (5,5) can be generated by using random() function and we use rand(), randn(), ranf(), randint() to generate random numbers. 
"""
random_array = np.random.randint(0, 10, size=(5, 5))
print("Random array of shape (5,5):\n", random_array)
print("\n")

# What does axis=0 vs axis=1 mean in np.sum()?
"""
axis = 0 means along the rows or operations perform on columns and axis = 1 means along the columns or operations along the rows  and when we use it in np.sum() function it works according to it.
"""

# Implementation
import numpy as np
np.random.seed(42)
n = 30
sensor_data = np.random.normal(loc=25, scale=2, size=n)
# Outliers
sensor_data[7] = 45
sensor_data[17] = 5
sensor_data[27] = 57
print("Sensor Data:\n", sensor_data)
print("\n")

# Rolling Statistics
window_size = 3
windows = np.lib.stride_tricks.sliding_window_view(
    sensor_data,
    window_shape=window_size
)
rolling_mean = np.mean(windows, axis=1)
rolling_std = np.std(windows, axis=1)
print("Rolling Mean:\n", rolling_mean)
print("\n")
print("Rolling Standard Deviation:\n", rolling_std)
print("\n")

# Z-Score Normalization
mean = np.mean(sensor_data)
std = np.std(sensor_data)
z_scores = (sensor_data - mean) / std
print("Mean:\n", mean)
print("\n")
print("Standard Deviation:\n", std)
print("\n")
print("Z-Scores:\n", z_scores)
print("\n")

# Detect Outliers
outlier_mask = np.abs(z_scores) > 2
print("Outlier Mask:\n", outlier_mask)
print("\n")
# Get Outlier Values
outliers = sensor_data[outlier_mask]
print("Outliers:\n", outliers)

